<a href="https://colab.research.google.com/github/shubhangi942/workshop/blob/main/pandas_basic5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importing pands

In [9]:
import pandas as pd

In [10]:
import numpy as np

##creating Series Object From List

In [11]:
# string
country=['India','pakistan','USA','Srilanka']

pd.Series(country)

0       India
1    pakistan
2         USA
3    Srilanka
dtype: object

In [12]:
marks=[67,57,88,100]
subjects=['maths','english','history','science']

pd.Series(marks,index=subjects)

maths       67
english     57
history     88
science    100
dtype: int64

In [18]:
#custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [ ]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

##creating series object from a dic

In [51]:
marks_1 = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks_1,name='shubhangi ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: shubhangi ke marks, dtype: int64

In [52]:
marks_2 = {
    'maths':67,
    'english':57,
    'science':np.nan,
    'hindi':100
}

marks_series_2 = pd.Series(marks_2,name='shubhangi ke marks')
marks_series_2

maths       67.0
english     57.0
science      NaN
hindi      100.0
Name: shubhangi ke marks, dtype: float64

#Series Attributes

In [53]:
marks_series

maths       67
english     57
science     89
hindi      100
Name: shubhangi ke marks, dtype: int64

In [54]:
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [58]:
marks_series.values

array([ 67,  57,  89, 100])

In [59]:
marks_series.dtype

dtype('int64')

In [60]:
marks_series.size

4

In [61]:
marks_series.size

4

In [62]:
c

NameError: name 'c' is not defined

In [63]:
check_unique.cumsum()
check_unique.cumprod()
check_unique.median()

NameError: name 'check_unique' is not defined

In [ ]:
marks_series.is_unique

check_unique.cumsum

In [22]:
#Reading a CSV

#index_col is a parameter used in pandas functions like read_csv() or read_excel().
#It tells pandas which column to use as the index.


movies = pd.read_csv(r'/content/bollywood.csv',index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [23]:
movies.head(10)

                                                      lead
movie
Uri: The Surgical Strike                     Vicky Kaushal
Battalion 609                                  Vicky Ahuja
The Accidental Prime Minister (film)           Anupam Kher
Why Cheat India                              Emraan Hashmi
Evening Shadows                           Mona Ambegaonkar
Soni (film)                           Geetika Vidya Ohlyan
Fraud Saiyaan                                 Arshad Warsi
Bombairiya                                    Radhika Apte
Manikarnika: The Queen of Jhansi            Kangana Ranaut
Thackeray (film)                       Nawazuddin Siddiqui

In [24]:
movies.tail(10)

                                        lead
movie
Raaz (2002 film)                  Dino Morea
Zameen (2003 film)                Ajay Devgn
Waisa Bhi Hota Hai Part II      Arshad Warsi
Devdas (2002 Hindi film)      Shah Rukh Khan
Kaante                      Amitabh Bachchan
Hum Tumhare Hain Sanam        Shah Rukh Khan
Aankhen (2002 film)         Amitabh Bachchan
Saathiya (film)                 Vivek Oberoi
Company (film)                    Ajay Devgn
Awara Paagal Deewana            Akshay Kumar

In [25]:
movies.sample()

                               lead
movie
Kis Kis Ki Kismat  Mallika Sherawat

In [26]:
movies.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [14]:
virat_kohli = pd.read_csv(r'/content/kohli_ipl.csv',index_col='match_no')
virat_kohli

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [15]:
virat_kohli.sort_values(ascending=False,by='runs').head(1).values[0]

array([113])

In [17]:
virat_kohli

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [27]:
movies.sort_index(ascending=False,inplace=True)

In [29]:
movies

                                        lead
movie
Zor Lagaa Ke...Haiya!          Meghan Jadhav
Zokkomon                     Darsheel Safary
Zindagi Tere Naam         Mithun Chakraborty
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi 50-50                    Veena Malik
...                                      ...
2 States (2014 film)            Arjun Kapoor
1971 (2007 film)              Manoj Bajpayee
1920: The Evil Returns           Vicky Ahuja
1920: London                   Sharman Joshi
1920 (film)                 Rajniesh Duggall

[1500 rows x 1 columns]

In [35]:
virat_kohli.sort_values(inplace=True,by='runs')
virat_kohli

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [36]:
virat_kohli

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [37]:
virat_kohli.count()

runs    215
dtype: int64

In [38]:
virat_kohli.sum()

runs    6634
dtype: int64

In [39]:
mean = virat_kohli.mean()
median = virat_kohli.median()
mode = virat_kohli.mode()
std = virat_kohli.std()
var = virat_kohli.var()
print('mean : ',mean, '\nmedian : ',median, '\nmode : ',mode,'\nstd : ', std, '\nvar : ',var)

mean :  runs    30.855814
dtype: float64
median :  runs    24.0
dtype: float64
mode :     runs
0     0
std :  runs    26.229801
dtype: float64
var :  runs    688.002478
dtype: float64

In [40]:
virat_kohli.max()

runs    113
dtype: int64

In [41]:
virat_kohli.describe()

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

#series indexing

In [43]:
x=pd.Series([12,13,14,35,33,44,56])
x

0    12
1    13
2    14
3    35
4    33
5    44
6    56
dtype: int64

In [44]:
x[5]

np.int64(44)

In [65]:
x[-1]

KeyError: -1

In [64]:
marks_series[-1]

<ipython-input-64-14301c43e6a1>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks_series[-1]

np.int64(100)

In [66]:
virat_kohli[5:16]

          runs
match_no
207          0
135          0
130          0
211          0
106          1
204          1
113          1
77           1
1            1
5            1
75           1

In [67]:
movies[::12]

                                          lead
movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zameer: The Fire Within             Ajay Devgn
Yeh Hai India                     Gavie Chahal
Woodstock Villa                  Sikander Kher
Waris Shah: Ishq Daa Waaris        Gurdas Maan
...                                        ...
Aetbaar                       Amitabh Bachchan
Aashiqui 2                   Aditya Roy Kapoor
Aakhari Decision                    Paul Sidhu
A Decent Arrangement              Shabana Azmi
36 China Town                   Akshaye Khanna

[125 rows x 1 columns]

In [68]:
movies[::2]

                                     lead
movie
Zor Lagaa Ke...Haiya!       Meghan Jadhav
Zindagi Tere Naam      Mithun Chakraborty
Zindagi 50-50                 Veena Malik
Zinda (film)                  Sanjay Dutt
Zid (2014 film)            Mannara Chopra
...                                   ...
3 Storeys                     Aisha Ahmed
3 Deewarein              Naseeruddin Shah
22 Yards                      Barun Sobti
1971 (2007 film)           Manoj Bajpayee
1920: London                Sharman Joshi

[750 rows x 1 columns]

#Editing series

In [69]:
marks_series

maths       67
english     57
science     89
hindi      100
Name: shubhangi ke marks, dtype: int64

In [70]:
marks_series

maths       67
english     57
science     89
hindi      100
Name: shubhangi ke marks, dtype: int64

In [71]:
marks_series[0]=100
marks_series

<ipython-input-71-fe70212a8a0e>:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[0]=100

maths      100
english     57
science     89
hindi      100
Name: shubhangi ke marks, dtype: int64

In [72]:
marks_series['sst']=100
marks_series

maths      100
english     57
science     89
hindi      100
sst        100
Name: shubhangi ke marks, dtype: int64

In [74]:
marks_series['history']=np.nan
marks_series

maths      100.0
english     57.0
science     89.0
hindi      100.0
sst        100.0
history      NaN
Name: shubhangi ke marks, dtype: float64

In [79]:
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [80]:
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [81]:
runs_ser[1:4]=100
runs_ser

0     13
1    100
2    100
3    100
4    100
dtype: int64

In [82]:
runs_ser[[0,3,4]]=[0,0,0]
runs_ser

0      0
1    100
2    100
3      0
4      0
dtype: int64

#Python Functions on series

In [83]:
print(len(runs_ser))
print(type(runs_ser))
print(dir(runs_ser))
print(sorted(runs_ser))
print(min(runs_ser))
print(max(runs_ser))

5
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']
[0, 0, 0, 100, 100]
0
100

In [89]:
list(marks_series)

[100.0, 57.0, 89.0, 100.0, 100.0, nan]

In [90]:
dict(marks_series)

{'maths': np.float64(100.0),
 'english': np.float64(57.0),
 'science': np.float64(89.0),
 'hindi': np.float64(100.0),
 'sst': np.float64(100.0),
 'history': np.float64(nan)}

In [91]:
'2 states (2014 film)' in movies

False

In [93]:
'renuka sapkale' in movies.values

False

In [94]:
'shubhangi' in movies.values

False

In [95]:
100+marks_series

maths      200.0
english    157.0
science    189.0
hindi      200.0
sst        200.0
history      NaN
Name: shubhangi ke marks, dtype: float64

In [97]:
virat_kohli >=50

           runs
match_no
8         False
87        False
93        False
91        False
206       False
...         ...
164        True
120        True
123        True
126        True
128        True

[215 rows x 1 columns]

In [99]:
virat_kohli[virat_kohli >=50]
(virat_kohli >=50).sum()

runs    50
dtype: int64

In [100]:
(virat_kohli ==0).sum()

runs    9
dtype: int64

#Questions based on real world example

In [104]:
 #find actors who have done more than 20 movies
num_movies = movies.value_counts()
num_movies[num_movies > 20]

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

In [117]:
import sys
sys.getsizeof(virat_kohli)

3472

In [119]:
import sys
sys.getsizeof(virat_kohli.astype('int32'))

2612

#Plotting histogram using pandas